// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Ordering.Infrastructure;

#nullable disable

namespace Portfolio.Ordering.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    partial class OrderingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_seq");

            modelBuilder.Entity("Portfolio.Ordering.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cancellation_key");

                    b.Property<string>("CancellationNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_note");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CheckoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("placed_at");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "Portfolio.Ordering.Domain.Order.Total#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("total_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CheckoutId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_checkout");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_number");

                    b.HasIndex("CustomerId", "PlacedAt", "Id")
                        .HasDatabaseName("ix_orders_customer_placed_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("orders", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_orders_cancellation", "(status = 'Cancelled') = (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('AwaitingPayment', 'Paid', 'Shipped', 'Delivered', 'Cancelled')");

                            t.HasCheckConstraint("ck_orders_total_positive", "total_amount > 0");

                            t.HasCheckConstraint("ck_orders_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("Portfolio.Ordering.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Portfolio.Ordering.Domain.OrderItem.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("unit_price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_items_quantity", "quantity BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_order_items_unit_price_positive", "unit_price_amount > 0");
                        });
                });

            modelBuilder.Entity("Portfolio.SharedKernel.Infrastructure.InboxMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Consumer", "MessageId")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_messages_processed_at");

                    b.ToTable("inbox_messages", "ordering");
                });

            modelBuilder.Entity("Portfolio.SharedKernel.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_version");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CausationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trace_state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_outbox_messages_aggregate_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_aggregate_version", "aggregate_version >= 1");

                            t.HasCheckConstraint("ck_outbox_messages_attempts", "attempts >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Ordering.Domain.OrderItem", b =>
                {
                    b.HasOne("Portfolio.Ordering.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("Portfolio.Ordering.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
